env:
  name: "Taxi-v3"
  config:

agent:
  learning_rate: 1.0e-4
  discount_factor: 0.99
  epsilon_start: 1.0
  epsilon_end: 0.1
  epsilon_decay: 0.99
  replay_buffer_episodes: 1000
  train_batch_size: 128
  train_epochs: 1000
  hidden_size: 64

training:
  num_episodes: 20000
  wait_time: 0
  save_interval: 1000
  train_frequency: 100
